### ISSUE TITLE
BingPic 接口 跳转路径错误

### ISSUE THREAD

**Issue by Tim-Paik** [Stapxs/Stapxs-Web-API#1]
访问 https://api.stapxs.cn/BingPic

预期结果

跳转至 https://cn.bing.com/th?id=OHR.TheNationaDay_ZH-CN5381900085_1920x1080.jpg

实际结果 

跳转至 https://api.stapxs.cn/th?id=OHR.TheNationaDay_ZH-CN5381900085_1920x1080.jpg

**Comment by Stapxs** [comment]
fixed main@3e5a35401a7b27e12417aab819e21a181162c270
